'use client'
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import Maincontext from "./context/Maincontext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Frank And Oak USA - Frank And Oak USA",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Maincontext>
          {children}
          </Maincontext>
      </body>
    </html>
  );
}
